export const searchnavbar = [
  {
    code: "PCEP",
    slug: "pceptrainingcourse",
    title: "Python Institute Certified Entry-Level Python Programmer",
    c_image: "/certification_img/python_logo/PCEP.webp",
  },
  {
    code: "PCAP",
    slug: "pcappreparationcourse",
    title: "Python Institute Certified Associate in Python Programming",
    c_image: "/certification_img/python_logo/PCAP.webp",
  },
  {
    code: "PCPP1",
    slug: "pcpp1training",
    title: "Certified Professional Python Programmer Level 1",
    c_image: "/certification_img/python_logo/PCPPL1.webp",
  },
  {
    code: "PCPP2",
    slug: "pcpp2course",
    title: "Certified Professional Python Programmer Level 2",
    c_image: "/certification_img/python_logo/PCPPL2.webp",
  },
  {
    code: "PCAT",
    slug: "pcatonlinecourse",
    title: "Certified Associate Tester with Python",
    c_image: "/certification_img/python_logo/PCAT.webp",
  },
  {
    code: "PCED",
    slug: "pcedcertificationpreparation",
    title: "Certified Entry-Level Data Analyst with Python",
    c_image: "/certification_img/python_logo/PCED.webp",
  },
  {
    code: "PCAD",
    slug: "pcadcertificationsyllabus",
    title: "Certified Associate Data Analyst with Python",
    c_image: "/certification_img/python_logo/PCAD.webp",
  },
  {
    code: "SC200",
    slug: "microsoftsecurityoperationsanalystcertification",
    title: "Microsoft Security Operations Analyst",
    c_image: "/certification_img/microsoft_logo/SC200.webp",
  },
  {
    code: "SC300",
    slug: "microsoftidentitymanagertraining",
    title: "Microsoft Identity and Access Administrator",
    c_image: "/certification_img/microsoft_logo/SC300.webp",
  },
  {
    code: "AZ104",
    slug: "microsoftazureadministratortrainingcourse",
    title: "Microsoft Azure Administrator",
    c_image: "/certification_img/microsoft_logo/AZ104.webp",
  },
  {
    code: "AZ204",
    slug: "az204trainingcourses",
    title: "Developing Solutions for Microsoft Azure",
    c_image: "/certification_img/microsoft_logo/AZ204.webp",
  },
  {
    code: "AZ500",
    slug: "microsoftazuresecuritytechnologiescourse",
    title: "Microsoft Azure Security Technologies",
    c_image: "/certification_img/microsoft_logo/AZ500.webp",
  },
  {
    code: "AZ305",
    slug: "az305trainingcourse",
    title: "Designing Microsoft Azure Infrastructure Solutions",
    c_image: "/certification_img/microsoft_logo/AZ305.webp",
  },
  {
    code: "AZ400",
    slug: "az400trainingonline",
    title: "Designing and Implementing Microsoft DevOps Solutions",
    c_image: "/certification_img/microsoft_logo/AZ400.webp",
  },
  {
    code: "SC100",
    slug: "microsoftcybersecuritycourseforbeginners",
    title: "Microsoft Cybersecurity Architect",
    c_image: "/certification_img/microsoft_logo/SC100.webp",
  },
  {
    code: "MB910",
    slug: "microsoftdynamics365traininginchennai",
    title: "Microsoft Dynamics 365 Fundamentals (CRM)",
    c_image: "/certification_img/microsoft_logo/MB910.webp",
  },
  {
    code: "MB920",
    slug: "microsoftdynamics365trainingcourses",
    title: "Microsoft Dynamics 365 Fundamentals (ERP)",
    c_image: "/certification_img/microsoft_logo/MB920.webp",
  },
  {
    code: "MB102",
    slug: "microsoft365administratortraining",
    title: "Microsoft 365 Administrator",
    c_image: "/certification_img/microsoft_logo/MB335.webp",
  },
  {
    code: "MB700",
    slug: "microsoftfinanceandoperationstraining",
    title:
      "Microsoft Dynamics 365 Finance and Operations Apps Solution Architect",
    c_image: "/certification_img/microsoft_logo/MB700.webp",
  },
  {
    code: "220-1101",
    slug: "comptiaacourseinchennai",
    title: "CompTIA A+",
    c_image: "/certification_img/comptia_logo/com220.webp",
  },
  {
    code: "N10-008",
    slug: "comptianetworkcertification",
    title: "CompTIA Network+",
    c_image: "/certification_img/comptia_logo/comn10.webp",
  },
  {
    code: "SY0-601 & SY0-701",
    slug: "comptiasecuritycourseinchennai",
    title: "CompTIA Security+",
    c_image: "/certification_img/comptia_logo/comsy0701.webp",
  },
  {
    code: "CV0-003",
    slug: "comptiacloudtrainingcenters",
    title: "CompTIA Cloud+",
    c_image: "/certification_img/comptia_logo/comcv0.webp",
  },
  {
    code: "XK0-005",
    slug: "comptialinuxtraining",
    title: "CompTIA Linux+",
    c_image: "/certification_img/comptia_logo/comxk0.webp",
  },
  {
    code: "CA0-003",
    slug: "comptiacybersecurityanalystcertification",
    title: "CompTIA Cybersecurity Analyst (CySA+)",
    c_image: "/certification_img/comptia_logo/comca0.webp",
  },
  {
    code: "CAS-004",
    slug: "comptiaadvancedsecuritypractitionertraining",
    title: "CompTIA Advanced Security Practitioner (CASP+)",
    c_image: "/certification_img/comptia_logo/comcas.webp",
  },
  {
    code: "PT0-002",
    slug: "comptiapentestcourse",
    title: "CompTIA PenTest+",
    c_image: "/certification_img/comptia_logo/compt0.webp",
  },
  {
    code: "DA0-001",
    slug: "comptiadatatraining",
    title: "CompTIA Data+",
    c_image: "/certification_img/comptia_logo/comda0.webp",
  },
  {
    code: "DS0-001",
    slug: "comptiadatasystraining",
    title: "CompTIA DataSys+",
    c_image: "/certification_img/comptia_logo/comds0.webp",
  },
  {
    code: "GMLE",
    slug: "giaccertificationexamcost",
    title: "GIAC Machine Learning Engineer",
    c_image: "/certification_img/giac_logo/gmle.webp",
  },
  {
    code: "GSOC",
    slug: "giacsecurityoperationscertifiedtraining",
    title: "GIAC Security Operations Certified",
    c_image: "/certification_img/giac_logo/gsoc.webp",
  },
  {
    code: "GISF",
    slug: "giacinformationsecurityfundamentalscertification",
    title: "GIAC Information Security Fundamentals",
    c_image: "/certification_img/giac_logo/gisf.webp",
  },
  {
    code: "GDSA",
    slug: "giacdefensiblesecurityarchitectcertification",
    title: "GIAC Defensible Security Architect",
    c_image: "/certification_img/giac_logo/gdsa.webp",
  },
  {
    code: "GISP",
    slug: "giacinformationsecurityProfessionalcertification",
    title: "GIAC Information Security Professional",
    c_image: "/certification_img/giac_logo/gisp.webp",
  },
  {
    code: "GSOM",
    slug: "giacsecurityoperationsmanagercertification",
    title: "GIAC Security Operations Manager",
    c_image: "/certification_img/giac_logo/gsom.webp",
  },
  {
    code: "GCIH",
    slug: "giaccertifiedincidenthandlercourse",
    title: "GIAC Certified Incident Handler",
    c_image: "/certification_img/giac_logo/gcih.webp",
  },
  {
    code: "GPEN",
    slug: "giacpenetrationtestertraining",
    title: "GIAC Penetration Tester",
    c_image: "/certification_img/giac_logo/gpen.webp",
  },
  {
    code: "GPYC",
    slug: "giacpythoncodertraining",
    title: "GIAC Python Coder",
    c_image: "/certification_img/giac_logo/gpyc.webp",
  },
  {
    code: "GCSA",
    slug: "giaccloudsecurityautomationtraining",
    title: "GIAC Cloud Security Automation",
    c_image: "/certification_img/giac_logo/gcsa.webp",
  },
  {
    code: "CISM",
    slug: "isacacybersecuritycertification",
    title: "ISACA Certified Information Security Manager",
    c_image: "/certification_img/isaca_logo/cism.webp",
  },
  {
    code: "CISA",
    slug: "informationsecuritygovernancecertification",
    title: "ISACA Certified Information Systems Auditor",
    c_image: "/certification_img/isaca_logo/cisa.webp",
  },
  {
    code: "CDPSE",
    slug: "isacadataprivacycertification",
    title: "ISACA Data Privacy Solutions Engineer",
    c_image: "/certification_img/isaca_logo/cdpse.webp",
  },
  {
    code: "CCA",
    slug: "isacacybersecurityauditcertificate",
    title: "ISACA Certified Cybersecurity Audit",
    c_image: "/certification_img/isaca_logo/cca.webp",
  },
  {
    code: "CDSF",
    slug: "isacadatasciencefundamentals",
    title: "ISACA Certified Data Science Fundamentals",
    c_image: "/certification_img/isaca_logo/cdsf.webp",
  },
  {
    code: "CSDF",
    slug: "isacacertificationcourses",
    title: "ISACA Certified Software Development Fundamentals",
    c_image: "/certification_img/isaca_logo/csdf.webp",
  },
]
