export const seometadatas = [
    {
        slug: "pceptrainingcourse",
        metatitle: "PCEP Training Course | Python Entry-Level Prep",
        metadescription : "Kickstart your Python career with our PCEP training course. Perfect for beginners preparing for the PCEP certification with hands-on practice.",
        metaimage: "/certification_img/python_logo/PCEP.webp",
    },
    {
        slug: "pcappreparationcourse",
        metatitle: "PCAP Preparation Course | Learn Python Certification",
        metadescription : "Master core Python programming with our PCAP preparation course. Get certified with expert-led training and practice tests for PCAP success.",
        metaimage: "/certification_img/python_logo/PCAP.webp",
    },
    {
        slug: "pcpp1training",
        metatitle: "PCPP1 Training | Advance Python Programming Course",
        metadescription : "Advance your skills with PCPP1 training. Prepare for the professional Python certification with real-world projects and expert guidance.",
        metaimage: "/certification_img/python_logo/PCPPL1.webp",
    },
    {
        slug: "pcpp2course",
        metatitle: "PCPP2 Course | Master Advanced Python Techniques",
        metadescription : "Become a Python expert with our PCPP2 course. Deepen your Python knowledge and prepare for the final certification in the PCAP series.",
        metaimage: "/certification_img/python_logo/PCPPL2.webp",
    },
    {
        slug: "pcatonlinecourse",
        metatitle: "PCAT Online Course | Prep for Pharmacy Admission Test",
        metadescription : "Ace the PCAT with our online course. Get expert strategies, practice questions, and test tips to boost your Pharmacy college admission score.",
        metaimage: "/certification_img/python_logo/PCAT.webp",
    },
    {
        slug: "pcedcertificationpreparation",
        metatitle: "PCED Certification Preparation | Exam Ready Course",
        metadescription : "Prepare for PCED certification with confidence. Get full syllabus coverage, mock tests, and expert guidance to clear your exam on first try",
        metaimage: "/certification_img/python_logo/PCED.webp",
    },
    {
        slug: "pcadcertificationsyllabus",
        metatitle: "PCAD Certification Syllabus | Full Course Outline",
        metadescription : "Explore the updated PCAD certification syllabus. Understand topics, exam modules, and skills covered to plan your professional learning path",
        metaimage: "/certification_img/python_logo/PCAD.webp",
    },
    {
        slug: "microsoftsecurityoperationsanalystcertification",
        metatitle: "Microsoft Security Analyst Certification | SC-200",
        metadescription : "Become a certified Security Operations Analyst with SC-200. Learn threat management and security monitoring techniques",
        metaimage: "/certification_img/microsoft_logo/SC200.png",
    },
    {
        slug: "microsoftidentitymanagertraining",
        metatitle: "Microsoft Identity Manager Training | Identity Solutions",
        metadescription : "Master identity and access management with Microsoft Identity Manager training. Learn to implement and manage identity solutions",
        metaimage: "/certification_img/microsoft_logo/SC300.png",
    },
    {
        slug: "microsoftazureadministratortrainingcourse",
        metatitle: "Azure Administrator Training | AZ-104 Certification",
        metadescription : "Prepare for the AZ-104 exam with Azure Administrator training. Learn to manage Azure resources, identities, and governance",
        metaimage: "/certification_img/microsoft_logo/AZ104.png",
    },
    {
        slug: "az204trainingcourses",
        metatitle: "AZ-204 Training Courses | Azure Developer Certification",
        metadescription : "Enhance your development skills with AZ-204 training. Learn to build and deploy Azure applications effectively",
        metaimage: "/certification_img/microsoft_logo/AZ204.png",
    },
    {
        slug: "microsoftazuresecuritytechnologiescourse",
        metatitle: "Azure Security Technologies Course | AZ-500 Prep",
        metadescription : "Secure your Azure environment with AZ-500 training. Learn to implement security controls and threat protection",
        metaimage: "/certification_img/microsoft_logo/AZ500.png",
    },
    {
        slug: "az305trainingcourse",
        metatitle: "AZ-305 Training Course | Azure Solutions Architect",
        metadescription : "Prepare for the AZ-305 exam with our training course. Learn to design Azure solutions and achieve certification success.",
        metaimage: "/certification_img/microsoft_logo/AZ305.png",
    },
    {
        slug: "az400trainingonline",
        metatitle: "AZ-400 Training Online | DevOps Engineer Certification",
        metadescription : "Advance your DevOps skills with AZ-400 online training. Learn continuous integration, delivery, and infrastructure as code.",
        metaimage: "/certification_img/microsoft_logo/AZ400.png",
    },
    {
        slug: "microsoftcybersecuritycourseforbeginners",
        metatitle: "Microsoft Cybersecurity Course | Beginner's Guide",
        metadescription : "Start your cybersecurity journey with Microsoft's beginner course. Learn fundamentals of security, compliance, and identity",
        metaimage: "/certification_img/microsoft_logo/SC100.png",
    },
    {
        slug: "microsoftdynamics365traininginchennai",
        metatitle: "Dynamics 365 Training in Chennai | CRM & ERP Skills",
        metadescription : "Enhance your business skills with Dynamics 365 training in Chennai. Learn CRM and ERP solutions for career advancement",
        metaimage: "/certification_img/microsoft_logo/MB910.png",
    },
    {
        slug: "microsoftdynamics365trainingcourses",
        metatitle: "Dynamics 365 Training Courses | Business Applications",
        metadescription : "Explore Microsoft Dynamics 365 training courses. Gain expertise in business applications, CRM, and ERP solutions",
        metaimage: "/certification_img/microsoft_logo/MB920.png",
    },
    {
        slug: "microsoft365administratortraining",
        metatitle: "Microsoft 365 Administrator Training | MS-100 & MS-101",
        metadescription : "Become a certified Microsoft 365 Administrator. Learn to manage user identities, security, and compliance in Microsoft 365",
        metaimage: "/certification_img/microsoft_logo/MB335.png",
    },
    {
        slug: "microsoftfinanceandoperationstraining",
        metatitle: "Microsoft Finance & Operations Training | ERP Solutions",
        metadescription : "Master financial and operational processes with Microsoft Finance & Operations training. Learn to optimize ERP solutions",
        metaimage: "/certification_img/microsoft_logo/MB700.png",
    },
    {
        slug: "comptiaacourseinchennai",
        metatitle: "CompTIA A+ Course in Chennai",
        metadescription : "Join the top-rated CompTIA A+ course in Chennai. Learn hardware, networking, and IT support to start your career in tech confidently",
        metaimage: "/certification_img/comptia_logo/com220.webp",
    },
    {
        slug: "comptianetworkcertification",
        metatitle: "CompTIA Network+ Certification | Networking Skills",
        metadescription : "Prepare for the CompTIA Network+ certification and build core skills in network infrastructure, protocols, security, and operations",
        metaimage: "/certification_img/comptia_logo/comn10.webp",
    },
    {
        slug: "comptiasecuritycourseinchennai",
        metatitle: "CompTIA Security+ Course Chennai | Cybersecurity Basics",
        metadescription : "Learn cybersecurity fundamentals with CompTIA Security+ in Chennai. Build skills in threat detection, risk management, and encryption",
        metaimage: "/certification_img/comptia_logo/comsy0701.webp",
    },
    {
        slug: "comptiacloudtrainingcenters",
        metatitle: "CompTIA Cloud+ Training Centers | Cloud Infrastructure",
        metadescription : "Find the best CompTIA Cloud+ training centers to learn cloud deployment, automation, and troubleshooting across platforms",
        metaimage: "/certification_img/comptia_logo/comcv0.webp",
    },
    {
        slug: "comptialinuxtraining",
        metatitle: "CompTIA Linux+ Training | Master Linux Administration",
        metadescription : "Enroll in CompTIA Linux+ training to master Linux system operations, shell scripting, network configurations, and cybersecurity",
        metaimage: "/certification_img/comptia_logo/comxk0.webp",
    },
    {
        slug: "comptiacybersecurityanalystcertification",
        metatitle: "CompTIA CySA+ Certification | Analyst Training Course",
        metadescription : "Get certified with CompTIA CySA+ and become a cybersecurity analyst skilled in threat intelligence, SIEM, and vulnerability management.",
        metaimage: "/certification_img/comptia_logo/comca0.webp",
    },
    {
        slug: "comptiaadvancedsecuritypractitionertraining",
        metatitle: "CompTIA CASP+ Training | Advanced Security Skills",
        metadescription : "Advance your security expertise with CompTIA CASP+ training. Learn enterprise security, risk analysis, and architecture solutions",
        metaimage: "/certification_img/comptia_logo/comcas.webp",
    },
    {
        slug: "comptiapentestcourse",
        metatitle: "CompTIA PenTest+ Course | Learn Ethical Hacking Skills",
        metadescription : "Master ethical hacking with CompTIA PenTest+ course. Learn penetration testing, vulnerability scanning, and exploitation techniques",
        metaimage: "/certification_img/comptia_logo/compt0.webp",
    },
    {
        slug: "comptiadatatraining",
        metatitle: "CompTIA Data+ Training | Data Analytics Certification",
        metadescription : "Start your data career with CompTIA Data+ training. Learn to interpret data, analyze trends, and support business decision-making",
        metaimage: "/certification_img/comptia_logo/comda0.webp",
    },
    {
        slug: "comptiadatasystraining",
        metatitle: "CompTIA DataSys+ Training | Database Admin Skills",
        metadescription : "Enroll in CompTIA DataSys+ training and learn to manage databases, ensure security, support SQL environments, and analyze system",
        metaimage: "/certification_img/comptia_logo/comds0.webp",
    },
    {
        slug: "giaccertificationexamcost",
        metatitle: "GIAC Certification Exam Cost",
        metadescription : "Understand the costs associated with GIAC certification exams. Plan your investment for a successful cybersecurity career",
        metaimage: "/certification_img/giac_logo/gmle.webp",
    },
    {
        slug: "giacsecurityoperationscertifiedtraining",
        metatitle: "GIAC Security Operations Training | GSOC Certification",
        metadescription : "Enhance your security operations skills with GIAC training. Prepare for GSOC certification and advance your cybersecurity career",
        metaimage: "/certification_img/giac_logo/gsoc.webp",
    },
    {
        slug: "giacinformationsecurityfundamentalscertification",
        metatitle: "",
        metadescription : "",
        metaimage: "/certification_img/giac_logo/gisf.webp",
    },
    {
        slug: "giacdefensiblesecurityarchitectcertification",
        metatitle: "GIAC Defensible Security Architect | GDSA Certification",
        metadescription : "Design robust security architectures with GIAC GDSA certification. Learn to build defensible and resilient systems",
        metaimage: "/certification_img/giac_logo/gdsa.webp",
    },
    {
        slug: "giacinformationsecurityProfessionalcertification",
        metatitle: "GIAC InfoSec Fundamentals Certification | Entry-Level",
        metadescription : "Begin your cybersecurity journey with GIAC Information Security Fundamentals certification. Learn core principles and practices",
        metaimage: "/certification_img/giac_logo/gisp.webp",
    },
    {
        slug: "giacsecurityoperationsmanagercertification",
        metatitle: "GIAC Security Operations Manager | GSOM Certification",
        metadescription : "Lead security operations with GIAC GSOM certification. Develop managerial skills for effective cybersecurity oversight.",
        metaimage: "/certification_img/giac_logo/gsom.webp",
    },
    {
        slug: "giaccertifiedincidenthandlercourse",
        metatitle: "GIAC Incident Handler Course | GCIH Certification",
        metadescription : "Respond to cyber threats effectively with GIAC GCIH certification. Learn incident handling and response techniques",
        metaimage: "/certification_img/giac_logo/gcih.webp",
    },
    {
        slug: "giacpenetrationtestertraining",
        metatitle: "GIAC Penetration Tester Training | GPEN Certification",
        metadescription : "Master ethical hacking with GIAC GPEN certification. Learn penetration testing methodologies and tools.",
        metaimage: "/certification_img/giac_logo/gpen.webp",
    },
    {
        slug: "giacpythoncodertraining",
        metatitle: "GIAC Python Coder Training | GCPY Certification",
        metadescription : "Develop secure coding skills with GIAC GCPY certification. Learn Python programming for cybersecurity applications",
        metaimage: "/certification_img/giac_logo/gpyc.webp",
    },
    {
        slug: "giaccloudsecurityautomationtraining",
        metatitle: "GIAC Cloud Security Automation | GCSA Certification",
        metadescription : "GIAC Cloud Security Automation | GCSA Certification",
        metaimage: "/certification_img/giac_logo/gcsa.webp",
    },
    {
        slug: "isacacybersecuritycertification",
        metatitle: "ISACA Cyber Security Certification | Advance Your Career",
        metadescription : "Boost your cyber security career with ISACA certification. Learn risk management, threat response, and governance best practices from experts",
        metaimage: "/certification_img/isaca_logo/cism.webp",
    },
    {
        slug: "informationsecuritygovernancecertification",
        metatitle: "Info Security Governance Cert | ISACA-Certified Course",
        metadescription : "Master governance and compliance with this ISACA-backed Information Security Governance certification. Ideal for IT risk & audit professionals",
        metaimage: "/certification_img/isaca_logo/cisa.webp",
    },
    {
        slug: "isacadataprivacycertification",
        metatitle: "ISACA Data Privacy Certification | Global Privacy Skills",
        metadescription : "Earn the ISACA data privacy certification and gain expertise in managing privacy frameworks, compliance laws, and data protection practices",
        metaimage: "/certification_img/isaca_logo/cdpse.webp",
    },
    {
        slug: "isacacybersecurityauditcertificate",
        metatitle: "ISACA Cybersecurity Audit Certificate | Online Training",
        metadescription : "Get certified in cybersecurity auditing with ISACA’s Cybersecurity Audit Certificate. Learn risk assessment, controls, and audit techniques",
        metaimage: "/certification_img/isaca_logo/cca.webp",
    },
    {
        slug: "isacadatasciencefundamentals",
        metatitle: "ISACA Data Science Fundamentals | Analytics Certification",
        metadescription : "Learn data analytics with ISACA’s Data Science Fundamentals. Ideal for beginners looking to understand data-driven decision-making",
        metaimage: "/certification_img/isaca_logo/cdsf.webp",
    },
    {
        slug: "isacacertificationcourses",
        metatitle: "ISACA Certification Courses | Cybersecurity & IT Audit",
        metadescription : "Explore top ISACA certification courses like CISA, CISM, CRISC, and CGEIT. Enhance your IT governance, audit, and security expertise",
        metaimage: "/certification_img/isaca_logo/csdf.webp",
    }

];